version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE') }}"
    schema: "{{ env_var('DBT_SCHEMA') }}"

    # For bigquery:
    # database: GCP_PROJECT_iD
    # schema: BQ_DATASET

    # For postgres:
    # database: production
    # schema: trips_data_all

    # loaded_at_field: record_loaded_at
    tables:
      - name: fhv_2019
      - name: fhv_all
      - name: green_all
      - name: yellow_all
        # freshness:
        # error_after: {count: 6, period: hour}
